### ISSUE TITLE
Category and Tag support

### ISSUE THREAD

**Issue by rebornix** [rebornix/OpenLiveWriter#4]
As we know Jekyll is static site generator, it doesn't have any database for aggregation data storage like `Category` and `Tag`. The aggregation only happens when Jekyll builds the site. So a proper way to allow users to use category or tag feature in OLW is adding a new xml in Jekyll site, containing below content 

```
<xml>
  <categories>
  {% for category in site.categories %} 
    <category>{{ category }}</cagegory>
  {% endfor %}
 </categories>
</xml>
```

Wordpress and Blogger hosts a specific file called `wlwmanifest.xml` for WLW configuration, maybe we can call it `olwmanifiest.xml`.

**Comment by rebornix** [comment]
Take this one myself.

**Comment by pekiZG** [comment]
sorry @rebornix Just moved to new place, no interwebs here ATM :(

**Comment by rebornix** [comment]
@pekizg no worries, we still have a lot of work to do :)

**Comment by rebornix** [comment]
Implement this feature in latest commit. @pekiZG I've made some basic abstraction for json rest related requests, take a look at it and tell me your ideas.
