### ISSUE TITLE
Support excerpt override

### ISSUE THREAD

**Issue by rebornix** [rebornix/OpenLiveWriter#5]
We can set `SupportsExcerpt` as true in GitHubPageClient and Jekyll allows you to override the excerpt by setting the value in Yaml Front Matter.

**Comment by SummerSun** [comment]
I can take a look at this, but I may need some time to wrap-up the code base.

**Comment by rebornix** [comment]
@SummerSun cool, looking forward to your pr.

**Comment by rebornix** [comment]
Actually this issue is a sub task of #6 . Let's use that issue to track.
